branches:
  - main

dryRun: true

plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/changelog'
  - '@semantic-release/git'
  # we use goreleaser to create the github release!
  #- '@semantic-release/github'
  - - '@semantic-release/exec'
    - publishCmd: |
        echo "${nextRelease.notes}" > /tmp/release-notes.md
        goreleaser release --release-notes /tmp/release-notes.md --rm-dist
