name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v3
        with:
          cache: true
          go-version: '>=1.19.1'

      - run: |
          go version
          go build -v -x -o build/sensorpush-proxy main.go
          ls -la build

      - if: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
        uses: goreleaser/goreleaser-action@v4
        with:
          install-only: true

      - if: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - if: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
        uses: cycjimmy/semantic-release-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
            @semantic-release/exec

      - uses: act10ns/slack@v1
        if: always()
        with:
          status: ${{ job.status }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
